name: 🧩 User Story
description: Create a new functional or technical user story
title: '[US] '
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Objective
        What is the main goal of this user story?

  - type: textarea
    id: objective
    attributes:
      label: Objective
      placeholder: Describe the purpose of this US...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## ✅ Acceptance Criteria
        What must be true for this US to be considered complete?

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Replace, remove or expand the examples below to match your US.
      placeholder: |
        - The user can...
        - The system displays...
        - Input is validated when...
        - A response is returned in...

  - type: markdown
    attributes:
      value: |
        ## 🔗 Related Links / Context
        Add any useful references (Epic, designs, technical doc, etc.)

  - type: textarea
    id: links
    attributes:
      label: Context / Resources
      placeholder: e.g. Related Epic #12, Figma link, etc.
