name: Auto-create PR on push to US branch

on:
  push:
    branches:
      - 'feat/#*/*'
      - 'fix/#*/*'
      - 'chore/#*/*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR already exists
        id: check_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const { data: prs } = await github.rest.pulls.list({
              ...context.repo,
              head: `${context.repo.owner}:${branch}`,
              state: 'open'
            });

            if (prs.length > 0) {
              console.log("Une PR existe déjà.");
              return;
            }

            const match = branch.match(/#(\d+)/);
            const issueNumber = match ? `#${match[1]} ` : '';
            const title = branch.replace(/[-_/]+/g, ' ').replace(/#\d+/, '').trim();

            await github.rest.pulls.create({
              ...context.repo,
              head: branch,
              base: "main",
              title: `${issueNumber}${title}`,
              body: `PR créée automatiquement pour ${issueNumber}\n\n> Vérifie le contenu et associe l'issue si ce n’est pas fait.`
            });

            console.log("✅ PR créée automatiquement.");
