name: Mark linked issue as "done" when PR is merged

on:
  pull_request:
    types: [closed]

jobs:
  label_done_if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Marquer l'issue liée comme "done"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const prBody = pr.body || "";
            const branch = pr.head.ref;

            // Extraire le numéro d'issue du corps ou du nom de branche
            const issueNumberMatch =
              prBody.match(/#(\d+)/) || branch.match(/#(\d+)/);

            if (!issueNumberMatch) {
              console.log("❌ Aucun numéro d'issue détecté dans la PR.");
              return;
            }

            const issue_number = Number(issueNumberMatch[1]);

            // Supprimer le label "in review" s'il existe
            try {
              await github.rest.issues.removeLabel({
                ...context.repo,
                issue_number,
                name: "in review"
              });
            } catch (error) {
              console.log("ℹ️ Aucun label 'in review' à retirer.");
            }

            // Ajouter le label "done"
            await github.rest.issues.addLabels({
              ...context.repo,
              issue_number,
              labels: ["done"]
            });

            console.log(`✅ L'issue #${issue_number} est maintenant marquée comme 'done'.`);
